### PR TITLE
refactor index.js

### PR DESCRIPTION
**Pull request by BePo65**
Just as a basis of discussion :-)

And:
perhaps the objects 'department', 'relatedTo' etc in config.js should be moved to a new object named e.g. 'targetFields'; this way these objects would be nicely bundeled and 'fields' would be unnecessary.

### CODE REVIEW

**Comment by kessler** [comment]
That's a huge refactor so I'll have to look into it more deeply, but just base on the fact that it "revives" the code to a more updated version of ecmascript I'm very positive about it.

Please sign the https://github.com/ironSource/opensource-contributor-license-agreement and I'll go over your PR in the meanwhile.

**Comment by kessler** [comment]
That's a huge refactor so I'll have to look into it more deeply, but just base on the fact that it "revives" the code to a more updated version of ecmascript I'm very positive about it.

Please sign the https://github.com/ironSource/opensource-contributor-license-agreement and I'll go over your PR in the meanwhile.

**Comment by kessler** [comment]
@BePo65 went over this PR, just waiting for you to sign the cla

**Comment by BePo65** [comment]
When refactoring, perhaps it would be a good idea, to switch from 'var' to 'const'/'let'?
I'd be willing to update the code in this way, if you like the idea.

**Pull request merged**
