### PR TITLE
update tests to current responses from npmjs.org

### PR DESCRIPTION
**Pull request by BePo65**
Updated the e2e tests to reflect the current version number of the packages on npmjs.org.
This would be the basis for refactoring index,js of the project.

### CODE REVIEW

**Comment by kessler** [comment]
Hi, Sorry for the late reply to this, finally found some time to merge all PRs, could you please follow the procedure at https://github.com/ironSource/opensource-contributor-license-agreement and I'll make sure it is merged in the next 7 days. Thank you for your PR!

**Comment by BePo65** [comment]
Hi,
contributing to an open source project under MIT license, I never had someone ask me to sign a license agreement (especially not one that didn't even mention the name of he project).
This is not a commercial product and I am not a contractor of ironSource even if this is your project.

Running under [MIT](https://github.com/ironSource/license-report/blob/master/LICENSE) license means that anybody can use the code as he likes. So for example you are free to go to my fork of your great project and copy any modifications I made into your project.
This is exactly what a github pull request does for you - copy my modifications from my project in a branch of your project.

Perhaps you ask the lawyers at ironSource if your are unsure what to do :-)

**Comment by BePo65** [comment]
Done

**Comment by kessler** [comment]
@BePo65 awesome, I'm on this

**Pull request merged**
