### PR TITLE
fix #39 (Bump ini from 1.3.5 to 1.3.8)

### PR DESCRIPTION
**Pull request by BePo65**
fix issue #39 (Bump ini from 1.3.5 to 1.3.8) by reinstalling all packages (deleted file `package-lock.json` and folder `node_modules` and executed `npm i`).

### CODE REVIEW

**Comment by kessler** [comment]
I merged the PR from dependabot, so we can close this right ?

**Comment by BePo65** [comment]
right :-)

**Comment by BePo65** [comment]
ups, too many pr for `(Bump ini from 1.3.5 to 1.3.8)`. In my version I simply deleted the package-lock.json and made a `npm i` that appeared cleaner than the solution from the dependabot. But that doesn't matter. 
On next occasion I repeat that step, if you agree.

**Comment by kessler** [comment]
for sure

**Pull request closed without merging**
