### PR TITLE
Allow fetching license info from `peerDependencies` and `optionalDependencies`

### PR DESCRIPTION
**Pull request by pubmikeb**
Add support of `peerDependencies` and `optionalDependencies`.

Reference: https://github.com/ironSource/license-report/issues/61

### CODE REVIEW

**Comment by pubmikeb** [comment]
@BePo65, could you, please, have a look why the _Node.js CI / build (10.x) (pull_request)_ is failed?
I don't see any suspicious points there. It looks like the DevOps/Mocha configuration issue, rather than the PR issue.

Thanks.

**Comment by BePo65** [comment]
That is my fault: I updated mocha to version 9 just to fix an issue from the github dependabot and here mocha dropped support for node v10 (as this felt out of LTS in march).
I didn't find the time to clear this with Yaniv and to drop the v10 support from the github actions.

So with your PR everything is fine,don't worry.

**Comment by pubmikeb** [comment]
> That is my fault: I updated mocha to version 9 just to fix an issue from the github dependabot and here mocha dropped support for node v10 (as this felt out of LTS in march).
> I didn't find the time to clear this with Yaniv and to drop the v10 support from the github actions.
> 
> So with your PR everything is fine,don't worry.

@BePo65, should I still do something to be able to merge this PR?

**Comment by BePo65** [comment]
No, we will do the rest (but please be patient, we are quite busy at the moment).

**Comment by BePo65** [comment]
The changes are part of the merged pr #65.
Thank you for contributing :-)

**Pull request closed without merging**
